# Change these first
owner: xxnet2017 # Your GitHub organization or username, where this repository lives
repo: xxnet-status # The name of this repository

sites:
  - name: "猩猩互联主页 (XXNet Website)"
    url: https://xxnet.online
  - name: "订阅服务&客户端API (Subscribe Service & Client API)"
    url: https://wall.rip
  - name: "Emby"
    url: https://cf.embyplus.club
  - name: 🇨🇳 转发-广州移动 (Forward-GuangZhouCM)
    check: "tcp-ping"
    url: $SECRET_SITE_GZCM
    port: 25036
  - name: 🇨🇳 转发-长沙联通 (Forward-ChangShaCU)
    check: "tcp-ping"
    url: $SECRET_SITE_CSCU
    port: 10393
  - name: 🇨🇳 转发-上海移动 (Forward-ShangHaiCM)
    check: "tcp-ping"
    url: $SECRET_SITE_SHCM
    port: 25108
  - name: 🇭🇰 核心节点-香港 (CoreNode-HongKong)
    check: "tcp-ping"
    url: $SECRET_SITE_HK
    port: 22
  - name: 🇯🇵 核心节点-日本 (CoreNode-Japan)
    check: "tcp-ping"
    url: $SECRET_SITE_JP
    port: 22
  - name: 🇹🇼 边缘节点-台湾 (EdgeNode-Taiwan)
    check: "tcp-ping"
    url: $SECRET_SITE_TW
    port: 22
  - name: 🇸🇬 边缘节点-新加坡 (EdgeNode-Singapore)
    check: "tcp-ping"
    url: $SECRET_SITE_SG
    port: 22
  - name: 🇺🇸 边缘节点-美国西部 (EdgeNode-AmericanWest)
    check: "tcp-ping"
    url: $SECRET_SITE_USW
    port: 22
  - name: 🇺🇸 边缘节点-美国东部 (EdgeNode-AmericanEast)
    check: "tcp-ping"
    url: $SECRET_SITE_USE
    port: 22
  - name: 🇩🇪 边缘节点-德国 (EdgeNode-German)
    check: "tcp-ping"
    url: $SECRET_SITE_DE
    port: 22

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.wall.rip
  baseUrl: /xxnet-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: 猩猩互联服务状态
  theme: ocean
  introTitle: "**猩猩互联服务状态**"
  introMessage: "猩猩互联服务状态是一个用于监控猩猩互联网站，APP，中转服务与边缘节点状态的站点，本站点仅提供部分核心区域的监控"
  navbar:
    - title: 状态
      href: /
    - title: 猩猩互联
      href: https://wall.rip

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  activeIncidents: 活动状态
  incidentReport: "#$NUMBER号事件报告 →"
  activeIncidentSummary: 开始于 $DATE，有 $POSTS 条报告
  incidentTitle:  $NUMBER号事件详情
  incidentDetails: 事件详情
  incidentFixed: 已修复
  incidentOngoing: 进行中
  incidentOpenedAt: 开始于
  incidentClosedAt: 结束于
  incidentSubscribe: 订阅更新
  incidentViewOnGitHub: 在Github上查看
  incidentCommentSummary: $AUTHOR 于 $DATE 发布
  incidentBack: ← 返回到全部时间
  pastIncidents: 过去的事件
  pastIncidentsResolved: 问题在$MINUTES分钟内被解决， 有$POSTS条报告
  liveStatus: 在线状态
  overallUptime: "服务在线率: $UPTIME"
  overallUptimeTitle: 服务在线率
  averageResponseTime: "平均响应时间: $TIMEms"
  averageResponseTimeTitle: 平均响应
  sevelDayResponseTime: 7天平均响应时间
  responseTimeMs: 响应时间(ms)
  loading: 加载中
  navGitHub: GitHub
  footer: ©2022 [猩猩互联](https://wall.rip), 由 [Upptime](https://upptime.js.org) 强力驱动
  rateLimitExceededTitle: 超过限速
  rateLimitExceededIntro: 您已超过一小时内可以执行的请求数，因此您必须等待才能再次访问此网站。或者，您可以添加 GitHub 个人访问令牌以继续使用该网站。
  rateLimitExceededWhatDoesErrorMean: 这个错误意味着什么?
  rateLimitExceededErrorMeaning: 本网站使用 GitHub API 访问有关我们网站状态的实时数据。默认情况下，GitHub 允许每个IP地址每小时进行60次请求，目前该配额已经被消耗殆尽
  rateLimitExceededErrorHowCanFix: 我该如何解决这个错误?
  rateLimitExceededErrorFix: 您可以再等待一个小时，您的 IP 地址限制将恢复。或者，您可以添加您的 GitHub 个人访问令牌，这会为您提供额外的每小时5,000次请求
  rateLimitExceededGeneratePAT: 学习如何生成一个个人访问令牌
  rateLimitExceededHasSet: 您拥有一个个人访问令牌集
  rateLimitExceededRemoveToken: 移除令牌
  rateLimitExceededGitHubPAT: GitHub个人访问令牌
  rateLimitExceededCopyPastePAT: 复制并且粘贴您的令牌
  rateLimitExceededSaveToken: 保存令牌
  errorTitle: 发生错误
  errorIntro: 尝试获取最新状态详细信息时出错
  errorText: 您可以稍候再试
  errorHome: 回到主页
  pastScheduledMaintenance: 过去的定期维护
  scheduledMaintenance: 定期维护
  scheduledMaintenanceSummaryStarted: 开始于$DATE，用时$DURATION分钟
  scheduledMaintenanceSummaryStarts: 计划开始于$DATE，用时$DURATION分钟
  startedAt: 开始于
  startsAt: 开始于
  duration: 计划维护时间
  durationMin: $DURATION分钟
  incidentCompleted: 已完成
  incidentScheduled: 计划中
  url: URL
  status: 状态
  history: 历史
  responseTime: 响应时间
  up: "在线"
  degraded: "服务降级"
  down: "离线"
  responseTimeGraphAlt: 响应时间图
  ms: ms
  responseTimeDay: 24小时响应时间
  responseTimeWeek: 1周响应时间
  responseTimeMonth: 1月响应时间
  responseTimeYear: 1年响应时间
  uptime: 全部响应时间
  uptimeDay: 24小时在线率
  uptimeWeek: 1周在线率
  uptimeMonth: 1月在线率
  uptimeYear: 1年在线率
  liveStatusHtmlComment: "<!--在线状态-->"
  allSystemsOperational: "当前所有系统运行正常"
  degradedPerformance: "服务出现降级"
  completeOutage: "所有服务出现故障"
  partialOutage: "部分服务出现故障"